site_name: Link 3.0
nav:
  - index.md
    
  - Getting Started:
    - GettingStarted/index.md
    - GettingStarted/Setup.md
    - GettingStarted/WStoLink.md
    - GettingStarted/SALTtoLink.md
    - GettingStarted/Installation.md
  
  - Upgradeto30.md
  - ReleaseNotes.md
  
  - Discussion:
    - Discussion/TechDetails.md
    - Discussion/Workspaces.md
    - Discussion/HowDoesItWork.md
    - Discussion/History.md
    
  - API:
    - API/index.md
    - API/Link.Add.md

    
theme:
  features:
    - navigation.indexes
  name: material
plugins:
    - search
    - with-pdf:
        custom_template_path: pdf_template
        cover_title: Link User Guide
        cover_subtitle: Link version 3.0
        cover_logo: img/cover_swirl.jpg
        font_family: Atkinson Hyperlegible
        debug_html: true
        author: ""
        toc_title: Contents